- name: Install Docker
  ansible.builtin.import_role:
    name: common
    tasks_from: docker

- name: Start a container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    restart: true
    ports:
      - "80:80"
    env:
      CATALOGUE_HOST :  catalogue-dev.rdevopsb87.online
      CATALOGUE_PORT :  "8080"
      USER_HOST :  user-dev.rdevopsb87.online
      USER_PORT :  "8080"
      CART_HOST :  cart-dev.rdevopsb87.online
      CART_PORT :  "8080"
      SHIPPING_HOST :  shipping-dev.rdevopsb87.online
      SHIPPING_PORT :  "8080"
      PAYMENT_HOST :  payment-dev.rdevopsb87.online
      PAYMENT_PORT :  "8080"

